[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.3"
tag_format = "v$version"
bump_message = "bump: Semantic Release Bot: Realease Version: $new_version 🤖🚀 [skip ci]"
version_files = [
    "setup.py:version",
    "package.json:version"
]